# config.toml
# Neovide configuration file

[font]
normal = ["Iosevka", "Symbols Nerd Font"]
bold = ["Iosevka Slab", "Symbols Nerd Font"]
italic = ["Iosevka Curly", "Symbols Nerd Font"]
bold_italic = ["Iosevka Curly Slab", "Symbols Nerd Font"]
size = 18
