# config.toml
# Neovide configuration file

fork = false
frame = "none"
idle = true
maximized = false
# neovim-bin = "/usr/bin/nvim"
no-multigrid = false
srgb = true
tabs = false
theme = "auto"
title-hidden = false
vsync = true
wsl = false

[font]
size = 16
hinting = "full"
edging = "antialias"
normal = [ [ "Iosevka Term", "Normal" ], [ "Symbols Nerd Font Mono", "Normal" ] ]
bold = [ [ "Iosevka Term Slab", "Bold" ], [ "Symbols Nerd Font Mono", "Bold" ] ]
italic = [ [ "Iosevka Term Curly", "Italic" ], [ "Symbols Nerd Font Mono", "Normal" ] ]
bold_italic = [ [ "Iosevka Term Curly Slab", "Bold Italic" ], [ "Symbols Nerd Font Mono", "Bold" ] ]
