# config.toml
# Neovide configuration file

fork = false
frame = "none"
idle = true
maximized = false
# neovim-bin = "/usr/bin/nvim"
no-multigrid = false
srgb = true
tabs = true
theme = "auto"
title-hidden = false
vsync = true
wsl = false

[font]
size = 12
hinting = "full"
edging = "antialias"
normal = ["Iosevka", "Symbols Nerd Font Mono"]
bold = ["Iosevka Slab", "Symbols Nerd Font Mono"]
italic = ["Iosevka Curly", "Symbols Nerd Font Mono"]
bold_italic = ["Iosevka Curly Slab", "Symbols Nerd Font Mono"]
