# config.toml
# Neovide configuration file

fork = false
frame = "none"
idle = true
maximized = false
# neovim-bin = "/usr/bin/nvim"
no-multigrid = false
srgb = true
tabs = true
theme = "auto"
title-hidden = false
vsync = true
wsl = false

[font]
size = 12
hinting = "full"
edging = "antialias"

normal = [ [ "Iosevka", "Normal" ], [ "Symbols Nerd Font Mono", "Normal" ] ]
bold = [ [ "Iosevka Slab", "Bold" ], [ "Symbols Nerd Font Mono", "Bold" ] ]
italic = [ [ "Iosevka Curly", "Italic" ], [ "Symbols Nerd Font Mono", "Italic" ] ]
bold_italic = [ [ "Iosevka Curly Slab", "Bold Italic" ], [ "Symbols Nerd Font Mono", "Bold Italic" ] ]
