[font]
size = 16

[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[scrolling]
history = 10000
multiplier = 2

[terminal.shell]
program = "/bin/bash"

[window]
decorations = "None"
opacity = {{ alpha*0.01 }}
dynamic_padding = true
startup_mode = "Windowed"
dynamic_title = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background            = "{{background}}"
foreground            = "{{color15}}"
dim_foreground        = "{{color7}}"
bright_foreground     = "{{color15}}"

[colors.cursor]
text                  = "{{color0}}"
cursor                = "{{color15}}"

[colors.vi_mode_cursor]
text                  = "{{color0}}"
cursor                = "{{color8}}"

[colors.search.matches]
foreground            = "{{color3}}"
background            = "{{color0}}"

[colors.search.focused_match]
foreground            = "{{color3}}"
background            = "{{color8}}"

[colors.hints.start]
foreground            = "{{color4}}"
background            = "{{color0}}"

[colors.hints.end]
foreground            = "{{color4}}"
background            = "{{color0}}"

[colors.line_indicator]
foreground            = "None"
background            = "None"

[colors.footer_bar]
foreground            = "{{color1}}"
background            = "{{color0}}"

[colors.selection]
text                  = "{{color6}}"
background            = "{{color8}}"

[colors.normal]
black                 = "{{color0}}"
red                   = "{{color1}}"
green                 = "{{color2}}"
yellow                = "{{color3}}"
blue                  = "{{color4}}"
magenta               = "{{color5}}"
cyan                  = "{{color6}}"
white                 = "{{color7}}"

[colors.bright]
black                 = "{{color8}}"
red                   = "{{color9}}"
green                 = "{{color10}}"
yellow                = "{{color11}}"
blue                  = "{{color12}}"
magenta               = "{{color13}}"
cyan                  = "{{color14}}"
white                 = "{{color15}}"
