# wallust 3.x

# backend = 'wal'
color_space = 'lab'
threshold = 10
palette = 'softdark16'
check_contrast = true
saturation = 45
alpha = 80

[ templates ]
alacritty.template = 'templates/alacritty.toml'
alacritty.target = '~/.config/alacritty/alacritty.toml'

zathura.template = 'templates/zathurarc'
zathura.target = '~/.config/zathura/zathurarc'

cava.template = 'templates/config.cava'
cava.target = '~/.config/cava/config'

aerc.template = 'templates/config.aerc'
aerc.target = '~/.config/aerc/stylesets/wal'

json.template = 'templates/colors.json'
json.target = '~/.cache/wal/colors.json'

kicad.template = 'templates/kicad_colorscheme.json'
kicad.target = '~/.config/kicad/8.0/colors/kiwal.json'

xresources.template = 'templates/Xresources'
xresources.target = '~/.config/Xresources'
