# wallust 3.x

backend = 'fastresize'
color_space = 'lch'
threshold = 12
palette = 'ansidark'
fallback_generator = "complementary"
check_contrast = true
saturation = 53
alpha = 90

[ templates ]
alacritty.template = 'alacritty.toml'
alacritty.target = '~/.config/alacritty/alacritty.toml'

zathura.template = 'zathurarc'
zathura.target = '~/.config/zathura/zathurarc'

cava.template = 'config.cava'
cava.target = '~/.config/cava/config'

aerc.template = 'config.aerc'
aerc.target = '~/.config/aerc/stylesets/wal'

json.template = 'colors.json'
json.target = '~/.cache/wal/colors.json'

kicad.template = 'kicad_colorscheme.json'
kicad.target = '~/.config/kicad/8.0/colors/kiwal.json'

xresources.template = 'Xresources'
xresources.target = '~/.config/Xresources'

wallpaper.template = 'wallpaper'
wallpaper.target = '~/.cache/wallust/wallpaper'
