# wallust 3.x

backend = 'full'
color_space = 'lch'
palette = 'ansidark16'
check_contrast = true
alpha = 90

[ templates ]
aerc = { template = '.config/aerc/stylesets/wal', target = '~/.config/aerc/stylesets/wal' }
alacritty = { template = '.config/alacritty/alacritty.toml', target = '~/.config/alacritty/alacritty.toml' }
cava = { template = '.config/cava/config', target = '~/.config/cava/config' }
dunst = { template = '.config/dunst/', target = '~/.config/dunst/' }
ghostty = { template = '.config/ghostty/config', target = '~/.config/ghostty/config' }
ghosttytheme = { template = '.config/ghostty/themes/wal', target = '~/.config/ghostty/themes/wal' }
hyprcolors = { template = '.config/hypr/hyprcolors.conf', target = '~/.config/hypr/hyprcolors.conf' }
json = { template = '.cache/wallust/colors.json', target = '~/.cache/wallust/colors.json' }
path = { template = '.cache/wallust/path', target = '~/.cache/wallust/path' }
kicad = { template = '.config/kicad/9.0/colors/kiwal.json', target = '~/.config/kicad/9.0/colors/kiwal.json' }
tofi = { template = '.config/tofi/', target = '~/.config/tofi/' }
waybar = { template = '.config/waybar/', target = '~/.config/waybar/' }
waybarcolors = { template = '.config/waybar/colors.css', target = '~/.config/waybar/colors.css' }
zathura = { template = '.config/zathura/zathurarc', target = '~/.config/zathura/zathurarc' }
