# wallust 3.x

backend = 'kmeans'
color_space = 'lab'
threshold = 10
palette = 'ansidark'
fallback_generator = "complementary"
check_contrast = true
saturation = 42
alpha = 80

[ templates ]
alacritty.template = 'alacritty.toml'
alacritty.target = '~/.config/alacritty/alacritty.toml'

zathura.template = 'zathurarc'
zathura.target = '~/.config/zathura/zathurarc'

cava.template = 'config.cava'
cava.target = '~/.config/cava/config'

aerc.template = 'config.aerc'
aerc.target = '~/.config/aerc/stylesets/wal'

json.template = 'colors.json'
json.target = '~/.cache/wallust/colors.json'

kicad.template = 'kicad_colorscheme.json'
kicad.target = '~/.config/kicad/8.0/colors/kiwal.json'

hyprcolors.template = 'hyprcolors.conf'
hyprcolors.target = '~/.config/hypr/hyprcolors.conf'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors.css'

foot.template = 'foot.ini'
foot.target = '~/.config/foot/foot.ini'

tofi.template = 'tofi.config'
tofi.target = '~/.config/tofi/config'

dunst.template = 'dunstrc'
dunst.target = '~/.config/dunst/dunstrc'
