# wallust 3.*

backend = 'wal'
color_space = 'lab'
# threshold = 19
palette = 'dark16'
# check_contrast = true
saturation = 40
alpha = 100

[ templates ]
alacritty.template = 'templates/alacritty_colors.toml'
alacritty.target = '~/.config/alacritty/alacritty_colors.toml'

zathura.template = 'templates/zathurarc'
zathura.target = '~/.config/zathura/zathurarc'

cava.template = 'templates/config.cava'
cava.target = '~/.config/cava/config'

aerc.template = 'templates/config.aerc'
aerc.target = '~/.config/aerc/stylesets/wal'

xresources.template = 'templates/colors.Xresources'
xresources.target = '~/.cache/wallust/colors.Xresources'

json.template = 'templates/colors.json'
json.target = '~/.cache/wal/colors.json'
