[colors.primary]
background            = "{color0}"
foreground            = "{color15}"
dim_foreground        = "{color7}"
bright_foreground     = "{color15}"

[colors.cursor]
text                  = "{color0}"
cursor                = "{color15}"

[colors.vi_mode_cursor]
text                  = "{color0}"
cursor                = "{color8}"

[colors.search.matches]
foreground            = "{color3}"
background            = "{color0}"

[colors.search.focused_match]
foreground            = "{color3}"
background            = "{color8}"

[colors.hints.start]
foreground            = "{color4}"
background            = "{color0}"

[colors.hints.end]
foreground            = "{color4}"
background            = "{color0}"

[colors.line_indicator]
foreground            = "None"
background            = "None"

[colors.footer_bar]
foreground            = "{color1}"
background            = "{color1}"

[colors.selection]
text                  = "{color6}"
background            = "{color8}"

[colors.normal]
black                 = "{color0}"
red                   = "{color1}"
green                 = "{color2}"
yellow                = "{color3}"
blue                  = "{color4}"
magenta               = "{color5}"
cyan                  = "{color6}"
white                 = "{color7}"

[colors.bright]
black                 = "{color8}"
red                   = "{color9}"
green                 = "{color10}"
yellow                = "{color11}"
blue                  = "{color12}"
magenta               = "{color13}"
cyan                  = "{color14}"
white                 = "{color15}"

# Alacritty will automatically calculate the dim colors based on the existing
# normal colors. Uncomment to have dim colors the same as normal colors with 
# the exception that white is still dimmed.
# [colors.dim]
# black                 = "{color0}"
# red                   = "{color1}"
# green                 = "{color2}"
# yellow                = "{color3}"
# blue                  = "{color4}"
# magenta               = "{color5}"
# cyan                  = "{color6}"
# white                 = "{color8}"

# vim: filetype=toml
