# tmux config
# v0.2

# Change leader keybinding
unbind 'C-b' # Unbind leader keybinding
set -g prefix 'C-Space' # Assign control-space as the new leader

# Change split behavior
unbind '%' # Unbind vertical split keybinding
bind '%' split-window -v -c "#{pane_current_path}" # Change vertical split behavior
unbind '"' # Unbind horizontal split keybinding
bind '"' split-window -h -c "#{pane_current_path}" # Change horizontal split behavior

# C-Space C-hjkl for switching panes
bind 'C-h' select-pane -L
bind 'C-j' select-pane -D
bind 'C-k' select-pane -U
bind 'C-l' select-pane -R

# C-Space hjkl for resizing panes
bind 'h' resize-pane -L 8
bind 'j' resize-pane -D 8
bind 'k' resize-pane -U 8
bind 'l' resize-pane -R 8

# Status style settings
set -g status-style bg=default

# Pane style settings
set -g pane-border-style fg=black
set -g pane-active-border-style fg=gray
set -g pane-border-status top
set -g pane-border-format ' #{pane_index}: #{pane_current_command} '
set -g pane-border-lines single
set -g pane-border-indicators colour


# Popup style settings
set -g popup-border-style fg=gray
set -g popup-border-lines heavy

# Neovim compatibility
set -sg escape-time 10
set -g focus-events on
set-option -sa terminal-features ',alacritty:RGB'

