ipc_socket = true
live_config_reload = true

[env]
TERM = "alacritty"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 14

[font.normal]
family = "IosevkaTerm Nerd Font"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 2

[shell]
args = ["--login"]
program = "/bin/bash"

[window]
decorations = "None"
decorations_theme_variant = "None"
dynamic_padding = true
opacity = 0.8
startup_mode = "Windowed"

[window.padding]
x = 2 
y = 0
