[general]
import = [
"~/.cache/wal/alacritty_colors.toml",
]
ipc_socket = true
live_config_reload = true


[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 12

[font.normal]
family = "Iosevka Term"

[font.bold]
family = "Iosevka Term Slab"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term Curly Slab"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term Curly"
style = "Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 2

[terminal.shell]
program = "/bin/bash"

[window]
decorations = "None"
decorations_theme_variant = "None"
opacity = 0.9
# opacity =  # BUG:
dynamic_padding = true
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 0 
y = 0

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background            = "#09121D"
foreground            = "#E7CEB3"
dim_foreground        = "#E7CEB3"
bright_foreground     = "#E7CEB3"

[colors.cursor]
text                  = "#09121D"
cursor                = "#E7CEB3"

[colors.vi_mode_cursor]
text                  = "#09121D"
cursor                = "#49545F"

[colors.search.matches]
foreground            = "#0E7DC4"
background            = "#09121D"

[colors.search.focused_match]
foreground            = "#0E7DC4"
background            = "#49545F"

[colors.hints.start]
foreground            = "#B9621B"
background            = "#09121D"

[colors.hints.end]
foreground            = "#B9621B"
background            = "#09121D"

[colors.line_indicator]
foreground            = "None"
background            = "None"

[colors.footer_bar]
foreground            = "#5A3F22"
background            = "#09121D"

[colors.selection]
text                  = "#266488"
background            = "#49545F"

[colors.normal]
black                 = "#25323F"
red                   = "#5A3F22"
green                 = "#C75A14"
yellow                = "#0E7DC4"
blue                  = "#B9621B"
magenta               = "#BE5B15"
cyan                  = "#266488"
white                 = "#E7CEB3"

[colors.bright]
black                 = "#49545F"
red                   = "#5A3F22"
green                 = "#C75A14"
yellow                = "#0E7DC4"
blue                  = "#B9621B"
magenta               = "#BE5B15"
cyan                  = "#266488"
white                 = "#E7CEB3"

# Alacritty will automatically calculate the dim colors based on the existing
# normal colors. Uncomment to have dim colors the same as normal colors with 
# the exception that white is still dimmed.
# [colors.dim]
# black                 = "#25323F"
# red                   = "#5A3F22"
# green                 = "#C75A14"
# yellow                = "#0E7DC4"
# blue                  = "#B9621B"
# magenta               = "#BE5B15"
# cyan                  = "#266488"
# white                 = "#49545F"

# vim: filetype=toml
