ipc_socket = true
live_config_reload = true

import = [
"~/.cache/wal/alacritty_colors.toml",
]

[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 12

[font.normal]
family = "Iosevka Term"

[font.bold]
family = "Iosevka Term Slab"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term Curly Slab"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term Curly"
style = "Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 2

[shell]
program = "/bin/bash"

[window]
decorations = "None"
decorations_theme_variant = "None"
opacity = 0.8
# opacity =  # BUG:
dynamic_padding = true
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 0 
y = 0

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background            = "#000000"
foreground            = "#E6E6E6"
dim_foreground        = "#706F67"
bright_foreground     = "#F4F3E9"

[colors.cursor]
text                  = "#000000"
cursor                = "#E6E6E6"

[colors.vi_mode_cursor]
text                  = "#000000"
cursor                = "#AEADA0"

[colors.search.matches]
foreground            = "#5D66B8"
background            = "#000000"

[colors.search.focused_match]
foreground            = "#5D66B8"
background            = "#AEADA0"

[colors.hints.start]
foreground            = "#BB8814"
background            = "#000000"

[colors.hints.end]
foreground            = "#BB8814"
background            = "#000000"

[colors.line_indicator]
foreground            = "None"
background            = "None"

[colors.footer_bar]
foreground            = "#BBB25E"
background            = "#000000"

[colors.selection]
text                  = "#976E10"
background            = "#AEADA0"

[colors.normal]
black                 = "#000000"
red                   = "#BBB25E"
green                 = "#BEAF3C"
yellow                = "#5D66B8"
blue                  = "#BB8814"
magenta               = "#3B74B0"
cyan                  = "#976E10"
white                 = "#706F67"

[colors.bright]
black                 = "#AEADA0"
red                   = "#F9ED7D"
green                 = "#FDEA50"
yellow                = "#7C88F5"
blue                  = "#FAB51B"
magenta               = "#4F9BEB"
cyan                  = "#BB8304"
white                 = "#F4F3E9"

# Alacritty will automatically calculate the dim colors based on the existing
# normal colors. Uncomment to have dim colors the same as normal colors with 
# the exception that white is still dimmed.
# [colors.dim]
# black                 = "#000000"
# red                   = "#BBB25E"
# green                 = "#BEAF3C"
# yellow                = "#5D66B8"
# blue                  = "#BB8814"
# magenta               = "#3B74B0"
# cyan                  = "#976E10"
# white                 = "#AEADA0"

# vim: filetype=toml
