ipc_socket = true
live_config_reload = true

import = [
"~/.cache/wal/alacritty_colors.toml",
]

[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 12

[font.normal]
family = "Iosevka Term"

[font.bold]
family = "Iosevka Term Slab"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term Curly Slab"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term Curly"
style = "Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 2

[shell]
program = "/bin/bash"

[window]
decorations = "None"
decorations_theme_variant = "None"
opacity = 0.8
# opacity =  # BUG:
dynamic_padding = true
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 0 
y = 0

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background            = "#000000"
foreground            = "#E6E6E6"
dim_foreground        = "#6C7372"
bright_foreground     = "#F0F7F6"

[colors.cursor]
text                  = "#000000"
cursor                = "#E6E6E6"

[colors.vi_mode_cursor]
text                  = "#000000"
cursor                = "#A9B2B2"

[colors.search.matches]
foreground            = "#BA7A29"
background            = "#000000"

[colors.search.focused_match]
foreground            = "#BA7A29"
background            = "#A9B2B2"

[colors.hints.start]
foreground            = "#81933D"
background            = "#000000"

[colors.hints.end]
foreground            = "#81933D"
background            = "#000000"

[colors.line_indicator]
foreground            = "None"
background            = "None"

[colors.footer_bar]
foreground            = "#63BFB9"
background            = "#000000"

[colors.selection]
text                  = "#3458A6"
background            = "#A9B2B2"

[colors.normal]
black                 = "#000000"
red                   = "#63BFB9"
green                 = "#2F92BE"
yellow                = "#BA7A29"
blue                  = "#81933D"
magenta               = "#2A7E74"
cyan                  = "#3458A6"
white                 = "#6C7372"

[colors.bright]
black                 = "#A9B2B2"
red                   = "#85FFF6"
green                 = "#3FC3FE"
yellow                = "#F8A236"
blue                  = "#ACC451"
magenta               = "#38A89B"
cyan                  = "#406FD7"
white                 = "#F0F7F6"

# Alacritty will automatically calculate the dim colors based on the existing
# normal colors. Uncomment to have dim colors the same as normal colors with 
# the exception that white is still dimmed.
# [colors.dim]
# black                 = "#000000"
# red                   = "#63BFB9"
# green                 = "#2F92BE"
# yellow                = "#BA7A29"
# blue                  = "#81933D"
# magenta               = "#2A7E74"
# cyan                  = "#3458A6"
# white                 = "#A9B2B2"

# vim: filetype=toml
