ipc_socket = true
live_config_reload = true

import = [
"~/.cache/wal/alacritty_colors.toml",
]

[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 12

[font.normal]
family = "Iosevka Term"

[font.bold]
family = "Iosevka Term Slab"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term Curly Slab"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term Curly"
style = "Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 2

[shell]
program = "/bin/bash"

[window]
decorations = "None"
decorations_theme_variant = "None"
opacity = 0.8
# opacity =  # BUG:
dynamic_padding = true
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 0 
y = 0

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background            = "#010101"
foreground            = "#C9C9C9"
dim_foreground        = "#737068"
bright_foreground     = "#F7F4EB"

[colors.cursor]
text                  = "#010101"
cursor                = "#C9C9C9"

[colors.vi_mode_cursor]
text                  = "#010101"
cursor                = "#B2AEA2"

[colors.search.matches]
foreground            = "#BE9442"
background            = "#010101"

[colors.search.focused_match]
foreground            = "#BE9442"
background            = "#B2AEA2"

[colors.hints.start]
foreground            = "#4081BF"
background            = "#010101"

[colors.hints.end]
foreground            = "#4081BF"
background            = "#010101"

[colors.line_indicator]
foreground            = "None"
background            = "None"

[colors.footer_bar]
foreground            = "#BFA968"
background            = "#010101"

[colors.selection]
text                  = "#2D7F8C"
background            = "#B2AEA2"

[colors.normal]
black                 = "#919191"
red                   = "#BFA968"
green                 = "#6689BF"
yellow                = "#BE9442"
blue                  = "#4081BF"
magenta               = "#BE6F23"
cyan                  = "#2D7F8C"
white                 = "#737068"

[colors.bright]
black                 = "#B2AEA2"
red                   = "#FFE18B"
green                 = "#88B7FF"
yellow                = "#FEC558"
blue                  = "#55ACFF"
magenta               = "#FE942F"
cyan                  = "#3CAABA"
white                 = "#F7F4EB"

# Alacritty will automatically calculate the dim colors based on the existing
# normal colors. Uncomment to have dim colors the same as normal colors with 
# the exception that white is still dimmed.
# [colors.dim]
# black                 = "#919191"
# red                   = "#BFA968"
# green                 = "#6689BF"
# yellow                = "#BE9442"
# blue                  = "#4081BF"
# magenta               = "#BE6F23"
# cyan                  = "#2D7F8C"
# white                 = "#B2AEA2"

# vim: filetype=toml
