ipc_socket = true
live_config_reload = true

import = [
"~/.cache/wal/alacritty_colors.toml",
]

[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 12

[font.normal]
family = "Iosevka Term"

[font.bold]
family = "Iosevka Term Slab"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term Curly Slab"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term Curly"
style = "Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 2

[shell]
program = "/bin/bash"

[window]
decorations = "None"
decorations_theme_variant = "None"
opacity = 0.9
# opacity =  # BUG:
dynamic_padding = true
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 0 
y = 0

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background            = "#101B29"
foreground            = "#D8C2AB"
dim_foreground        = "#D8C2AB"
bright_foreground     = "#D8C2AB"

[colors.cursor]
text                  = "#101B29"
cursor                = "#D8C2AB"

[colors.vi_mode_cursor]
text                  = "#101B29"
cursor                = "#525E6E"

[colors.search.matches]
foreground            = "#EE3B12"
background            = "#101B29"

[colors.search.focused_match]
foreground            = "#EE3B12"
background            = "#525E6E"

[colors.hints.start]
foreground            = "#3477C1"
background            = "#101B29"

[colors.hints.end]
foreground            = "#3477C1"
background            = "#101B29"

[colors.line_indicator]
foreground            = "None"
background            = "None"

[colors.footer_bar]
foreground            = "#694C26"
background            = "#101B29"

[colors.selection]
text                  = "#BC4B6D"
background            = "#525E6E"

[colors.normal]
black                 = "#2F3D50"
red                   = "#694C26"
green                 = "#962622"
yellow                = "#EE3B12"
blue                  = "#3477C1"
magenta               = "#C17D34"
cyan                  = "#BC4B6D"
white                 = "#D8C2AB"

[colors.bright]
black                 = "#525E6E"
red                   = "#694C26"
green                 = "#962622"
yellow                = "#EE3B12"
blue                  = "#3477C1"
magenta               = "#C17D34"
cyan                  = "#BC4B6D"
white                 = "#D8C2AB"

# Alacritty will automatically calculate the dim colors based on the existing
# normal colors. Uncomment to have dim colors the same as normal colors with 
# the exception that white is still dimmed.
# [colors.dim]
# black                 = "#2F3D50"
# red                   = "#694C26"
# green                 = "#962622"
# yellow                = "#EE3B12"
# blue                  = "#3477C1"
# magenta               = "#C17D34"
# cyan                  = "#BC4B6D"
# white                 = "#525E6E"

# vim: filetype=toml
