[general]
import = [
"~/.cache/wal/alacritty_colors.toml",
]
ipc_socket = true
live_config_reload = true


[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 12

[font.normal]
family = "Iosevka Term"

[font.bold]
family = "Iosevka Term Slab"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term Curly Slab"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term Curly"
style = "Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 2

[terminal.shell]
program = "/bin/bash"

[window]
decorations = "None"
decorations_theme_variant = "None"
opacity = 0.9
# opacity =  # BUG:
dynamic_padding = true
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 0 
y = 0

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background            = "#041422"
foreground            = "#E3ECEF"
dim_foreground        = "#E3ECEF"
bright_foreground     = "#E3ECEF"

[colors.cursor]
text                  = "#041422"
cursor                = "#E3ECEF"

[colors.vi_mode_cursor]
text                  = "#041422"
cursor                = "#445665"

[colors.search.matches]
foreground            = "#3B8ED6"
background            = "#041422"

[colors.search.focused_match]
foreground            = "#3B8ED6"
background            = "#445665"

[colors.hints.start]
foreground            = "#E0A124"
background            = "#041422"

[colors.hints.end]
foreground            = "#E0A124"
background            = "#041422"

[colors.line_indicator]
foreground            = "None"
background            = "None"

[colors.footer_bar]
foreground            = "#724D27"
background            = "#041422"

[colors.selection]
text                  = "#3B6A8B"
background            = "#445665"

[colors.normal]
black                 = "#1F3446"
red                   = "#724D27"
green                 = "#397883"
yellow                = "#3B8ED6"
blue                  = "#E0A124"
magenta               = "#A2842F"
cyan                  = "#3B6A8B"
white                 = "#E3ECEF"

[colors.bright]
black                 = "#445665"
red                   = "#724D27"
green                 = "#397883"
yellow                = "#3B8ED6"
blue                  = "#E0A124"
magenta               = "#A2842F"
cyan                  = "#3B6A8B"
white                 = "#E3ECEF"

# Alacritty will automatically calculate the dim colors based on the existing
# normal colors. Uncomment to have dim colors the same as normal colors with 
# the exception that white is still dimmed.
# [colors.dim]
# black                 = "#1F3446"
# red                   = "#724D27"
# green                 = "#397883"
# yellow                = "#3B8ED6"
# blue                  = "#E0A124"
# magenta               = "#A2842F"
# cyan                  = "#3B6A8B"
# white                 = "#445665"

# vim: filetype=toml
